/** Lowercase reserved handle segments — block exact match after normalize. */
export const RESERVED_HANDLE_WORDS: ReadonlySet<string> = new Set([
  'admin',
  'administrator',
  'root',
  'system',
  'support',
  'help',
  'official',
  'nimon',
  'api',
  'auth',
  'login',
  'logout',
  'signup',
  'register',
  'profile',
  'settings',
  'mono',
  'monos',
  'story',
  'stories',
  'learn',
  'collection',
  'collections',
  'saved',
  'bookmark',
  'bookmarks',
  'followers',
  'following',
  'user',
  'users',
  'creator',
  'creators',
  'public',
  'private',
  'null',
  'undefined',
  'me',
]);

export function isReservedHandle(handleLower: string): boolean {
  return RESERVED_HANDLE_WORDS.has(handleLower);
}
